export default {
  menu: {
    name: 'Crayon Shin-chan',
    menuName: 'Menu',
    type: 'Type',
    url: 'Route',
    icon: 'Icon',
    createAt: 'Create Time',
    updateAt: 'Update Time',
    permission: 'Button Permission',
    action: 'Action',
    closeAll: 'Close All',
    closeOther: 'Close Other',
  },
  home: {
    title1: 'Project Introduction',
    text1: 'The project is built on technologies such as Vue 3, Vite, Pinia, TypeScript, Ant Design Vue, ECharts, and others, and it encapsulates common functionalities for a system backend.',
    title2: 'technology stack',
    text2: 'Development tools',
    text3: 'Programming language',
    text4: 'Build tools',
    text5: 'Front-end framework',
    text6: 'Route tool',
    text7: 'State management',
    text8: 'UI framework',
    text9: 'Visualization',
    text10: 'Rich text',
    text11: 'Tool library',
    text12: 'CSS pre-compiled',
    text13: 'HTTP tool',
    text14: 'Git hook tool',
    text15: 'Code standards or coding conventions',
    text16: 'Commit conventions',
    text17: 'CI/CD tool',
    text18: 'Multi-language',
    text19: 'draggable',
    content1: 'Visual Studio Code',
    content2: 'TypeScript + JavaScript',
    content3: 'vite4',
    content4: 'Vue3',
    content5: 'Vue-Router4',
    content6: 'Pinia',
    content7: 'ant-design-vue',
    content8: 'ECharts5',
    content9: 'wangeditor5',
    content10: 'dayjs + countup.js',
    content11: 'sass',
    content12: 'axios',
    content13: 'husky',
    content14: 'prettier + eslint',
    content15: 'commitizen + commitlint',
    content16: 'github action',
    content17: 'vue118',
    content18: 'vuedraggable',
    title3: 'Production environment dependencies',
    title4: 'Directory structure'
  },
  user: {
    phone: 'phone',
    department: 'department',
    authority: 'authority',
    addUser: 'Add User',
    editUser: 'Edit User',
    exit: 'Exit',
  },
  role: {
    addRole: 'Add Role',
    editRole: 'Edit Role',
  },
  product: {
    name: 'Product Name',
    address: 'Product Address',
    desc: 'Product Description',
    enable: 'Status',
    imgUrl: 'Product Image',
    newPrice: 'New Price',
    oldPrice: 'Old Price',
    createAt: 'Create Time',
    updateAt: 'Update Time',
  },
  login: {
    login: 'Login',
    passwordLogin: 'Password Login',
    phoneLogin: 'Phone Login',
    rememberPassword: 'Remember Password',
    userName: 'Account',
    password: 'Password',
    code: 'Code',
    pleaseInputAccount: 'Please Input Account!',
    pleaseInputPassword: 'Please Input Password!',
    pleaseInputPhone: 'Please Input Phone!',
    pleaseInputCode: 'Please Input Code!',
    getCode: 'Get Code',
  },
  story: {
    input: 'Please Input Story...',
    add: 'Add Story',
    title: 'Story Title',
    inputTitle: 'Please Input Story Title',
  },
  form: {
    search: 'Search',
    reset: 'Reset',
    submit: 'Submit',
    name: 'Name',
    realname: 'Real Name',
    cellphone: 'Phone',
    enable: 'Status',
    password: 'Password',
    createAt: 'Create Time',
    updateAt: 'Update Time',
    department: 'Department',
    role: 'Role',
    intro: 'Permission Introduction',
    leader: 'Leader',
    add: 'Add',
    start: 'open',
    disable: 'close',
    inputName: 'Please Input Name',
    inputRealname: 'Please Input Real Name',
    inputCellphone: 'Please Input Phone',
    inputSelectEnable: 'Please Select Status',
    inputPassword: 'Please Input Password',
    inputIntro: 'Please Input Permission Introduction',
    selectDepartment: 'Please Select Department',
    selectRole: 'Please Select Role',
    collapse: 'Collapse',
    expand: 'Expand',
    action: 'Action',
    edit: 'Edit',
    delete: 'Delete',
    selectIntro: 'Please Select Permission',
  },
  notification: {
    title: 'Notification',
  },
  analysis: {
    categoryCount: 'Category Count',
    categorySale: 'Category Sale',
    categoryFavor: 'Category Favor',
    addressSale: 'Address Sale',
    AmountList: 'Amount List',
  }
}
