export default {
  menu: {
    name: 'Crayon Shin-chan',
  },
  user: {
    phone: 'phone',
    department: 'department',
  },
  login: {
    login: 'Login',
    passwordLogin: 'Password Login',
    phoneLogin: 'Phone Login',
    rememberPassword: 'Remember Password',
    userName: 'Account',
    password: 'Password',
    pleaseInputAccount: 'Please Input Account!',
    pleaseInputPassword: 'Please Input Password!',
    pleaseInputPhone: 'Please Input Phone!',
    pleaseInputCode: 'Please Input Code!',
    getCode: 'Get Code',
  },
  form: {
    search: 'Search',
    reset: 'Reset',
    submit: 'Submit',
    name: 'Name',
    realname: 'Real Name',
    cellphone: 'Phone',
    enable: 'Status',
    createAt: 'Create Time',
    updateAt: 'Update Time',
    add: 'Add',
    start: 'open',
    disable: 'close',
    inputName: 'Please Input Name',
    inputRealname: 'Please Input Real Name',
    inputCellphone: 'Please Input Phone',
    inputSelectEnable: 'Please Select Status',
  }
}
