export default {
  menu: {
    name: 'Crayon Shin-chan',
    menuName: 'Menu',
    type: 'Type',
    url: 'Route',
    icon: 'Icon',
    createAt: 'Create Time',
    updateAt: 'Update Time',
    permission: 'Button Permission',
    action: 'Action',
  },
  user: {
    phone: 'phone',
    department: 'department',
    addUser: 'Add User',
    editUser: 'Edit User',
  },
  role: {
    addRole: 'Add Role',
    editRole: 'Edit Role',
  },
  product: {
    name: 'Product Name',
    address: 'Product Address',
    desc: 'Product Description',
    enable: 'Status',
    imgUrl: 'Product Image',
    newPrice: 'New Price',
    oldPrice: 'Old Price',
    createAt: 'Create Time',
    updateAt: 'Update Time',
  },
  login: {
    login: 'Login',
    passwordLogin: 'Password Login',
    phoneLogin: 'Phone Login',
    rememberPassword: 'Remember Password',
    userName: 'Account',
    password: 'Password',
    pleaseInputAccount: 'Please Input Account!',
    pleaseInputPassword: 'Please Input Password!',
    pleaseInputPhone: 'Please Input Phone!',
    pleaseInputCode: 'Please Input Code!',
    getCode: 'Get Code',
  },
  form: {
    search: 'Search',
    reset: 'Reset',
    submit: 'Submit',
    name: 'Name',
    realname: 'Real Name',
    cellphone: 'Phone',
    enable: 'Status',
    password: 'Password',
    createAt: 'Create Time',
    updateAt: 'Update Time',
    department: 'Department',
    role: 'Role',
    intro: 'Permission Introduction',
    leader: 'Leader',
    add: 'Add',
    start: 'open',
    disable: 'close',
    inputName: 'Please Input Name',
    inputRealname: 'Please Input Real Name',
    inputCellphone: 'Please Input Phone',
    inputSelectEnable: 'Please Select Status',
    inputPassword: 'Please Input Password',
    inputIntro: 'Please Input Permission Introduction',
    selectDepartment: 'Please Select Department',
    selectRole: 'Please Select Role',
    collapse: 'Collapse',
    expand: 'Expand',
    action: 'Action',
    edit: 'Edit',
    delete: 'Delete',
    selectIntro: 'Please Select Permission',
  },
  notification: {
    title: 'Notification',
  }
}
