export default {
  menu: {
    name: '蜡笔小新',
    menuName: '菜单',
    type: '类型',
    url: '路由',
    icon: '图标',
    createAt: '创建时间',
    updateAt: '更新时间',
    permission: '按钮权限',
    action: '操作',
  },
  user: {
    phone: '手机号',
    department: '部门',
    authority: '权限',
    addUser: '新增用户',
    editUser: '编辑用户',
    exit: '退出'
  },
  role: {
    addRole: '新增角色',
    editRole: '编辑角色'
  },
  product: {
    name: '商品名称',
    address: '商品地址',
    desc: '商品描述',
    enable: '状态',
    imgUrl: '商品图片',
    newPrice: '新价格',
    oldPrice: '原价格',
    createAt: '创建时间',
    updateAt: '更新时间',
  },
  login: {
    login: '登录',
    passwordLogin: '密码登录',
    phoneLogin: '手机号登录',
    rememberPassword: '记住密码',
    userName: '账号',
    password: '密码',
    pleaseInputAccount: '请输入账号!',
    pleaseInputPassword: '请输入密码!',
    pleaseInputPhone: '请输入手机号!',
    pleaseInputCode: '请输入验证码!',
    getCode: '获取验证码'
  },
  form: {
    search: '搜索',
    reset: '重置',
    submit: '提交',
    name: '用户名',
    realname: '真实姓名',
    cellphone: '手机号',
    password: '密码',
    enable: '状态',
    createAt: '创建时间',
    updateAt: '更新时间',
    department: '部门',
    role: '角色',
    intro: '权限介绍',
    leader: '负责人',
    add: '新增',
    start: '启用',
    disable: '禁用',
    inputName: '请输入用户名',
    inputRealname: '请输入真实姓名',
    inputCellphone: '请输入手机号',
    inputSelectEnable: '请选择用户状态',
    inputPassword: '请输入密码',
    inputIntro: '请输入权限介绍',
    selectDepartment: '请选择部门',
    selectRole: '请选择角色',
    collapse: '收起',
    expand: '展开',
    action: '操作',
    edit: '编辑',
    delete: '删除',
    selectIntro: '请选择权限',
  },
  notification: {
    title: '通知',
  },
}
