export default {
  menu: {
    name: '蜡笔小新',
    menuName: '菜单',
    type: '类型',
    url: '路由',
    icon: '图标',
    createAt: '创建时间',
    updateAt: '更新时间',
    permission: '按钮权限',
    action: '操作',
    closeAll: '关闭所有',
    closeOther: '关闭其他'
  },
  home: {
    title1: '项目简介',
    text1: '项目基于vue3、vite、pinia、typescript、ant-design-vue、echarts等技术搭建，封装了系统后台常见功能。',
    title2: '技术栈',
    text2: '开发工具',
    text3: '编程语言',
    text4: '构建工具',
    text5: '前端框架',
    text6: '路由工具',
    text7: '状态管理',
    text8: 'UI 框架',
    text9: '可视化',
    text10: '富文本',
    text11: '工具库',
    text12: 'css 预编译',
    text13: 'HTTP工具',
    text14: 'Git hook 工具',
    text15: '代码规范',
    text16: '提交规范',
    text17: '自动部署',
    text18: '多语言',
    text19: '拖拽',
    content1: 'Visual Studio Code',
    content2: 'TypeScript + JavaScript',
    content3: 'vite4',
    content4: 'Vue3',
    content5: 'Vue-Router4',
    content6: 'Pinia',
    content7: 'ant-design-vue',
    content8: 'ECharts5',
    content9: 'wangeditor5',
    content10: 'dayjs + countup.js',
    content11: 'sass',
    content12: 'axios',
    content13: 'husky',
    content14: 'prettier + eslint',
    content15: 'commitizen + commitlint',
    content16: 'github action',
    content17: 'vue118',
    content18: 'vuedraggable',
    title3: '生产环境依赖',
    title4: '目录结构'
  },
  user: {
    phone: '手机号',
    department: '部门',
    authority: '权限',
    addUser: '新增用户',
    editUser: '编辑用户',
    exit: '退出'
  },
  role: {
    addRole: '新增角色',
    editRole: '编辑角色'
  },
  product: {
    name: '商品名称',
    address: '商品地址',
    desc: '商品描述',
    enable: '状态',
    imgUrl: '商品图片',
    newPrice: '新价格',
    oldPrice: '原价格',
    createAt: '创建时间',
    updateAt: '更新时间',
  },
  login: {
    login: '登录',
    passwordLogin: '密码登录',
    phoneLogin: '手机号登录',
    rememberPassword: '记住密码',
    userName: '账号',
    password: '密码',
    code: '验证码',
    pleaseInputAccount: '请输入账号!',
    pleaseInputPassword: '请输入密码!',
    pleaseInputPhone: '请输入手机号!',
    pleaseInputCode: '请输入验证码!',
    getCode: '获取验证码'
  },
  story: {
    input: '请输入内容...',
    add: '添加故事',
    title: '故事标题',
    inputTitle: '请输入故事标题',
  },
  form: {
    search: '搜索',
    reset: '重置',
    submit: '提交',
    name: '用户名',
    realname: '真实姓名',
    cellphone: '手机号',
    password: '密码',
    enable: '状态',
    createAt: '创建时间',
    updateAt: '更新时间',
    department: '部门',
    role: '角色',
    intro: '权限介绍',
    leader: '负责人',
    add: '新增',
    start: '启用',
    disable: '禁用',
    inputName: '请输入用户名',
    inputRealname: '请输入真实姓名',
    inputCellphone: '请输入手机号',
    inputSelectEnable: '请选择用户状态',
    inputPassword: '请输入密码',
    inputIntro: '请输入权限介绍',
    selectDepartment: '请选择部门',
    selectRole: '请选择角色',
    collapse: '收起',
    expand: '展开',
    action: '操作',
    edit: '编辑',
    delete: '删除',
    selectIntro: '请选择权限',
  },
  notification: {
    title: '通知',
  },
  analysis: {
    categoryCount: '类目统计',
    categorySale: '类目销售',
    categoryFavor: '类目收藏',
    addressSale: '地区销售',
    AmountList: '销售额类目',
  }
}
